
services:
  postgres:
    image: postgres
    container_name: employee-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: redis:7
    container_name: employee-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data
    command: [ "redis-server", "--appendonly", "yes" ]


volumes:
  pgdata:
  redisdata: